### PR TITLE
Do not execute on focus by default

### PR DESCRIPTION
**Pull request by stepzhou**
## Description

Change default to false since we've found the re-execute behavior confusing/annoying.

Resolves PDS-2422

## Test plan

Test by adding local views package on a view and verifying that switching tabs and back doesn't cause a task to re-execute.

### CODE REVIEW

**Comment by stepzhou** [comment]
cc: @joshma

**Comment by leeweisberger** [comment]
I like this setting... I'm still not sure why it's annoying? This should just revalidate in the background - if there are no changes then no changes are made. It seems like most users would want this and as I user I expect that applications do this and aren't out of date

**Comment by joshma** [comment]
This isn't always in the background. So maybe that's a bug. But for example, if I have a task that fails, and I switch windows, when I try to go back to Studio this causes it to refetch and I lose the state of the previous run.

But I think generally this is not an assumption users find obvious. This is OK for us to do for our own things but I think it's unexpected behavior.

**Comment by stepzhou** [comment]
My argument is that tasks are not quite as light-weight as API endpoints, so we shouldn't apply the same data consistency standards to them. Default false is more reasonable to me in that lens

**Review by leeweisberger — APPROVED** [review]

**Pull request merged**
